version: "3.9"
services:
  buttress:
    build: ../
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      NODE_ENV: "production"
      BUTTRESS_APP_TITLE: "ButtressJS"
      BUTTRESS_APP_CODE: "buttressjs"
      BUTTRESS_APP_PROTOCOL: "http"
      BUTTRESS_APP_PATH: "/code"
      BUTTRESS_HOST_URL: "https://localhost:6000"
      BUTTRESS_REST_LISTEN_PORT: "8080"
      BUTTRESS_SOCK_LISTEN_PORT: "8081"
      BUTTRESS_MONGO_URL: "mongodb://mongodb"
      BUTTRESS_REDIS_PORT: "6379"
      BUTTRESS_REDIS_HOST: "redis"
      BUTTRESS_REST_APP: "primary"
      BUTTRESS_SOCKET_APP: "primary"
      BUTTRESS_LOGGING_LEVEL: "info"
      BUTTRESS_LOGGING_SLOW: "TRUE"
      BUTTRESS_LOGGING_SLOW_TIME: 2
